#!/bin/bash
#     _     _
#    | |__ (_)_ __  ___ _   _ _ __   ___
#    | '_ \| | '_ \/ __| | | | '_ \ / __|
#    | |_) | | | | \__ \ |_| | | | | (__
#    |_.__/|_|_| |_|___/\__, |_| |_|\___|
#                       |___/
# Author: galaxy-cli
# Project: https://github.com/galaxy-cli/binsync
# binsync -  binsync is a Bash script that scans and updates my ~/scripts and ~/.local/bin directories

dst_dir="$HOME/.local/bin"
src_dir="$HOME/scripts"

# Recursively find all files in $src_dir
find "$src_dir" -type f | while read -r src_file; do
    filename="$(basename "$src_file")"
    # Find all files with the same name in $dst_dir (could be multiple)
    find "$dst_dir" -type f -name "$filename" | while read -r dst_file; do
        # Only copy if the files are different
        if ! cmp -s "$src_file" "$dst_file"; then
            cp "$src_file" "$dst_file"
            echo "Updated $dst_file with $src_file"
        fi
    done
done
