#!/bin/bash

src_dir="$HOME/scripts"
dst_dir="$HOME/.local/bin"

# Recursively find all files in $src_dir
find "$src_dir" -type f | while read -r src_file; do
    filename="$(basename "$src_file")"
    # Find all files with the same name in $dst_dir (could be multiple)
    find "$dst_dir" -type f -name "$filename" | while read -r dst_file; do
        # Only copy if the files are different
        if ! cmp -s "$src_file" "$dst_file"; then
            cp "$src_file" "$dst_file"
            echo "Updated $dst_file with $src_file"
        fi
    done
done